export const cartActionTypes = ({
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    CLEAR_CART_ITEM: 'CLEAR_CART_ITEM',
    CLEAR_CART: 'CLEAR_CART'
})
